server:
  tomcat:
    uri-encoding: UTF-8
  port: 11111

spring:
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    allow-bean-definition-overriding: true
  freemarker:
    template-loader-path:
      - classpath:/templates
      - file:${site.location}/storage/templates
    cache: false
    check-template-location: true
    charset: utf-8
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
      auto_import: /utils.ftl as utils
    flyway:
      enabled: false
      baseline-on-migrate: true
      encoding: UTF-8
      locations: classpath:scripts/migration

mybatis:
  mapper-locations: com.mezjh.kcaforum.**.dao
  configuration:
    map-underscore-to-camel-case: true

shiro:
  web:
    enabled: true
  annotations:
    enabled: false
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /error/reject.html
  sessionManager:
    cookie:
      maxAge: 604800
  rememberMeManager:
    cookie:
      maxAge: 604800



# site.options.theme: [default|classic]
site:
  version: 0.0.1
  location: ${user.dir}
  controls:
    # 发布文章开关
    post: true
    # 评论开关
    comment: true
  options:
    theme: classic
    storage_max_width: 800
    storeage_limit_size: 2
    editor: markdown