server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /kca

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: com.mezjh.kcaforum.**.dao
  configuration:
    map-underscore-to-camel-case: true
